services:
  app:
    container_name: ecommerce_api
    build: .
    profiles: ["app"]
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - ecommerce_network

  mysql:
    container_name: ecommerce_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ecommerce
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - ecommerce_network

networks:
  ecommerce_network: